server:
  port: 9999
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.182.141:2181
  application:
    name: agent-server
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.182.141:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
seata:
  enabled: true
  application-id: agent-server-seata
  tx-service-group: agent-server-tx-group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      agent-server-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
